[package]
name = "aqlink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aqlink"

[dependencies]
rocket = "0.5"
rusqlite = { version = "0.32", features = ["bundled", "array"] }
rand = "0.8"
